### ISSUE TITLE
Support attach requests

### ISSUE THREAD

**Issue by Gama11** [vshaxe/hxcpp-debugger#1]

**Comment by Yphotsmith** [comment]
Resolve

**Comment by nulld** [comment]
It works now. But there is a crash right after detach, when I trying to start new listening thread. Looks like it's related to this issue https://github.com/HaxeFoundation/hxcpp/issues/730 Made a pull request to hxcpp , that fixes this https://github.com/HaxeFoundation/hxcpp/pull/735
