### ISSUE TITLE
it's hxcpp-debugger & not hxcpp-debug-server

### ISSUE THREAD

**Issue by kaefert** [vshaxe/hxcpp-debugger#11]
Your plugin's "homepage" @ https://marketplace.visualstudio.com/items?itemName=vshaxe.hxcpp-debugger says to put `-lib hxcpp-debug-server` into `build.hxml` which will make vscode tell the user to install hxcpp-debug-server by running `haxelib install hxcpp-debug-server` which results in the error `Error: No such Project : hxcpp-debug-server`.

I believe that it should read `-lib hxcpp-debugger` (I'm a noob though, just have been trying to get into Haxe for the last few days - so I might be wrong)

**Comment by Gama11** [comment]
The readme is correct, see my reply here: https://github.com/vshaxe/vshaxe/issues/299#issuecomment-423655736

**Comment by kaefert** [comment]
whups, sorry. Thanks.
