### ISSUE TITLE
conditional breakpoints support

### ISSUE THREAD

**Issue by nulld** [vshaxe/hxcpp-debugger#12]
![example](https://user-images.githubusercontent.com/2820168/46635694-efc71980-cb5d-11e8-85c2-8f3a36e379d5.gif)

**Comment by Gama11** [comment]
Is it necessary to prefix expressions with `this` for it to work (like in the watch panel)? If so, it seems like that shouldn't be required.

**Comment by nulld** [comment]
Yes, for now, it required. Good point, will think about it.

**Comment by nulld** [comment]
@Gama11 it works now without requiring `this.`, but it's more performance draining solution. I'm not sure, what's the lesser of two evils... Can you test it for your project with two options? You can easily switch it here: https://github.com/vshaxe/hxcpp-debugger/blob/80ab728efa896019fca5d3fb93eb97f3e106a4ea/hxcpp-debug-server/hxcpp/debug/jsonrpc/Server.hx#L501 with last `bool` parameter. `true` means include members to interpreter context.
