### ISSUE TITLE
Breakpoints not getting hit

### ISSUE THREAD

**Issue by tbrosman** [vshaxe/hxcpp-debugger#13]
(Note: this might just be an issue with my setup.)

vshaxe-hxcpp-debugger version: 1.1.0

I have attempted to use the hxcpp-debugger extension with both Haxe 3.4.7 and Haxe 4.0.0-preview.5. In both cases, I have been able to run my compiled binary via Debug -> Start Debugging, but my breakpoints don't get hit.

My hxml file looks like this:

```hxml
-cp src
-lib hxcpp

# VSCode debugger
-lib hxcpp-debug-server

-main pong.Main
-debug
-cpp bin/cpp
```

I wasn't sure if it was necessary to include hxcpp as well. The configurations in my launch.json contains one entry:

```json
{
    "name": "Hxcpp",
    "type": "hxcpp",
    "request": "launch",
    "program": "${workspaceRoot}/bin/cpp/Main-debug.exe"
}
```

I'm using Visual Studio 2015 Community Edition.

Any idea what I might be missing?

A related question: what's the best way to see the trace output of the debug server? (E.g. the one listening on port 6972) I'm not sure which process is hosting it.

**Comment by nulld** [comment]
I just noticed, that there is a problem with hitting breakpoint on first line in `main` function - will look into it. If it your case, could you try to set breakpoint on any later line, and confirm that it works propertly?
If not - attach the output of  `DEBUG CONSOLE` (Ctrl + Shift + Y), please.

**Comment by tbrosman** [comment]
@nulld In the below code I have a breakpoint on every trace statement.

```haxe
package pong;

class Main
{
    public static function main():Void
    {
        trace("HELLO WORLD");
        trace(1);
        trace(2);
    }
}
```

Here is the debug console output:
```
src/pong/Main.hx:7: HELLO WORLD
src/pong/Main.hx:8: 1
src/pong/Main.hx:9: 2
```

No breakpoints are hit.

**Comment by nulld** [comment]
@tbrosman,
weird..
I don't see `Debug Server Started` and `Debug server connected!` messages in your output. Looks like debug server not using at all. Could you show your `\bin\cpp\src\__boot__.cpp`? Or you can zip all `bin` folder and send me to nulldivide at gmail com. 

Everything looks good with your `hxml` `Main.hx` - at least I can't reproduce the problem with them.

**Comment by tbrosman** [comment]
@nulld ~~I'm hitting a different issue now: "Debug adapter process has terminated unexpectedly" I am not sure what changed.~~

(**Edit**: Never mind, I accidentally deleted the 'bin' directory from my program path. Apparently that's the error you get. Weird. Now it's back to the old behavior of just not connecting at all.)

Here is my `__boot__.cpp`:

```cpp
// Generated by Haxe 4.0.0-preview.5+7eb789f54
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_pong_Main
#include <pong/Main.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
hx::RegisterResources( hx::GetResources() );
::haxe::Log_obj::__register();
::pong::Main_obj::__register();
::Std_obj::__register();
::haxe::Log_obj::__boot();
}

```

The only instance of the string "debug" I see in src (besides `#ifdef HXCPP_DEBUGGER`) is at the end of `__files.cpp`:

```cpp
void __files__boot() { __hxcpp_set_debugger_info(hx::__hxcpp_all_classes, hx::__hxcpp_all_files_fullpath); }
```

Does this look correct?

**Comment by nulld** [comment]
@tbrosman,

No, it isn't correct. There is no debug-server initialization at all.
Bellow, for example, part of boots genereted in mine environment (Haxe
Compiler 4.0.0-preview.5+7eb789f54, hxcpp:4.0.4).
I don't understand what differs in our setup. 

Could you add `--macro hxcpp.debug.jsonrpc.Macro.injectServer()` to you `build.hxml`? Seems, that automatically injection not works in your environment, for some reason.


void __boot_all()
{
__files__boot();
hx::RegisterResources( hx::GetResources() );
::hxcpp::debug::jsonrpc::eval::Token_obj::__register();
::hxcpp::debug::jsonrpc::eval::_Interp::Stop_obj::__register();
::hxcpp::debug::jsonrpc::eval::FieldKind_obj::__register();
::hxcpp::debug::jsonrpc::eval::FieldAccess_obj::__register();
::hxcpp::debug::jsonrpc::eval::ModuleDecl_obj::__register();
::hxcpp::debug::jsonrpc::eval::Error_obj::__register();
::hxcpp::debug::jsonrpc::eval::CType_obj::__register();
::hxcpp::debug::jsonrpc::eval::Expr_obj::__register();
::hxcpp::debug::jsonrpc::eval::Const_obj::__register();
::hxcpp::debug::jsonrpc::Value_obj::__register();
::hxcpp::debug::jsonrpc::VarType_obj::__register();
::haxe::io::Error_obj::__register();
::haxe::io::Encoding_obj::__register();
::ValueType_obj::__register();
::sys::net::Host_obj::__register();
::hxcpp::debug::jsonrpc::Server_obj::__register();
::hxcpp::debug::jsonrpc::eval::Parser_obj::__register();
::hxcpp::debug::jsonrpc::_Server::References_obj::__register();
::hxcpp::debug::jsonrpc::Protocol_obj::__register();
::haxe::Log_obj::__register();
::haxe::EntryPoint_obj::__register();
::cpp::vm::Debugger_obj::__register();
::sys::net::Socket_obj::__register();
::sys::net::_Socket::SocketOutput_obj::__register();
::sys::net::_Socket::SocketInput_obj::__register();
::pong::Main_obj::__register();
::hxcpp::debug::jsonrpc::eval::Tools_obj::__register();
::hxcpp::debug::jsonrpc::eval::Interp_obj::__register();
::hxcpp::debug::jsonrpc::VariablesPrinter_obj::__register();
::hxcpp::debug::jsonrpc::_Protocol::NotificationMethod_Impl__obj::__register
();
::hxcpp::debug::jsonrpc::_Protocol::RequestMethod_Impl__obj::__register();
::hxcpp::debug::jsonrpc::PathHelper_obj::__register();
::hxcpp::debug::jsonrpc::Macro_obj::__register();
::haxe::io::StringInput_obj::__register();
::haxe::io::Path_obj::__register();
::haxe::io::Eof_obj::__register();
::haxe::io::BytesOutput_obj::__register();
::haxe::io::Output_obj::__register();
::haxe::io::BytesInput_obj::__register();
::haxe::io::Input_obj::__register();
::haxe::io::BytesBuffer_obj::__register();
::haxe::io::Bytes_obj::__register();
::haxe::format::JsonPrinter_obj::__register();
::haxe::format::JsonParser_obj::__register();
::haxe::ds::_GenericStack::GenericStackIterator_hxcpp_debug_jsonrpc_eval_Token_obj::__register
();
::haxe::ds::StringMap_obj::__register();
::haxe::ds::ObjectMap_obj::__register();
::haxe::ds::IntMap_obj::__register();
::haxe::ds::GenericStack_hxcpp_debug_jsonrpc_eval_Token_obj::__register();
::haxe::ds::_GenericStack::GenericStackIterator_obj::__register();
::haxe::ds::GenericCell_obj::__register();
::haxe::ds::GenericCell_hxcpp_debug_jsonrpc_eval_Token_obj::__register();
::haxe::ds::EnumValueMap_obj::__register();
::haxe::ds::TreeNode_obj::__register();
::haxe::ds::BalancedTree_obj::__register();
::haxe::Utf8_obj::__register();
::haxe::Timer_obj::__register();
::haxe::MainLoop_obj::__register();
::haxe::MainEvent_obj::__register();
::haxe::IMap_obj::__register();
::cpp::vm::Thread_obj::__register();
::cpp::vm::Mutex_obj::__register();
::cpp::vm::Lock_obj::__register();
::cpp::vm::Deque_obj::__register();
::cpp::vm::ThreadInfo_obj::__register();
::cpp::vm::StackFrame_obj::__register();
::cpp::vm::Parameter_obj::__register();
::cpp::Lib_obj::__register();
::Type_obj::__register();
::Sys_obj::__register();
::StringTools_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::Reflect_obj::__register();
::IntIterator_obj::__register();
::EReg_obj::__register();
::Date_obj::__register();
::hxcpp::debug::jsonrpc::eval::Token_obj::__boot();
::hxcpp::debug::jsonrpc::eval::_Interp::Stop_obj::__boot();
::hxcpp::debug::jsonrpc::eval::FieldKind_obj::__boot();
::hxcpp::debug::jsonrpc::eval::FieldAccess_obj::__boot();
::hxcpp::debug::jsonrpc::eval::ModuleDecl_obj::__boot();
::hxcpp::debug::jsonrpc::eval::Error_obj::__boot();
::hxcpp::debug::jsonrpc::eval::CType_obj::__boot();
::hxcpp::debug::jsonrpc::eval::Expr_obj::__boot();
::hxcpp::debug::jsonrpc::eval::Const_obj::__boot();
::hxcpp::debug::jsonrpc::Value_obj::__boot();
::hxcpp::debug::jsonrpc::VarType_obj::__boot();
::haxe::io::Error_obj::__boot();
::haxe::io::Encoding_obj::__boot();
::ValueType_obj::__boot();
::cpp::vm::Debugger_obj::__init__();
::sys::net::Host_obj::__init__();
::cpp::vm::Debugger_obj::__boot();
::haxe::Log_obj::__boot();
::haxe::EntryPoint_obj::__boot();
::hxcpp::debug::jsonrpc::Protocol_obj::__boot();
::hxcpp::debug::jsonrpc::_Server::References_obj::__boot();
::hxcpp::debug::jsonrpc::eval::Parser_obj::__boot();
::hxcpp::debug::jsonrpc::Server_obj::__boot();
::sys::net::Host_obj::__boot();
}



пн, 22 окт. 2018 г., 2:52 Tommy Brosman <notifications@github.com>:

**Comment by tbrosman** [comment]
@nulld Ah okay, I'll try that next.

Here's a self-contained project that reproduces (on my machine, at least) this issue: https://github.com/tbrosman/vshaxe-hxcpp-debugger-issue-13-repro

FYI I'm using [lix](https://github.com/lix-pm/lix.client/) to manage dependencies. I see that the macro injection happens via extraParams.hxml. Where does this normally get included/run from?

**Comment by tbrosman** [comment]
@nulld I figured it out. When I added the dependency for hxcpp-debug-server, I created the stub hxml for lix manually (as far as I can tell there's no "local file" Haxelib source in lix). Apparently what lix actually does is keep extraParams.hxml around by copying it directly into the stub: https://github.com/lix-pm/lix.client/blob/master/src/lix/client/Libraries.hx

I've added the macro argument in and everything works now (minus some unrelated issue with not being able to continue to the next breakpoint after initially breaking). Thanks for the help!

**Comment by tbrosman** [comment]
P.S.: I moved my repo to https://github.com/tbrosman/vshaxe-hxcpp-debugger-and-lix (though GitHub does automatic redirects). I'm going to try to turn this into a "this is how you use lix + vshaxe" thing.

**Comment by nulld** [comment]
@tbrosman,
Good to know, that your problem is solved. 
Are you going to request some changes in lix, or just describe the approach?

Anyways, let me know, which additional setup steps are required with lix usage, please. I'm going to write to README about it.

Btw, found related issue in lix project https://github.com/lix-pm/lix.client/issues/10#issuecomment-336673441

**Comment by tbrosman** [comment]
@nulld So far my approach is kind of a hack. Having `haxelib dev` support in lix would still mean the full folder path would show up in my hxml (which I want to avoid). I'm guessing this is partially why it isn't supported: your hxml would contain some random filepath, which would be useless for other people checking out your repository. I'm discussing this with some others in https://gitter.im/lix-pm/Lobby if you are interested.

**Comment by Gama11** [comment]
I've decided to publish `hcxpp-debug-server` to Haxelib after all. We already do the same for [`test-adapter`](https://github.com/vshaxe/haxe-test-adapter), which has a pretty similar setup, and it makes life a lot easier for lix users (even though it violates the original idea of extension and lib never being able to go out of sync). I've considered using the new `lix dev` feature, but that still doesn't help that much (you can't commit the `hxcpp-debug-server.hxml from that if you don't want CI to fail etc).

Also, it makes sure nobody can steal the name of the library on Haxelib. :)
