### ISSUE TITLE
Type check not working in conditional breakpoints

### ISSUE THREAD

**Issue by sano98** [vshaxe/hxcpp-debugger#17]
I wanted to use a conditional breakpoint that should trigger when a general function (like a superclass constructor or a function that checks all onscreen objects for mouseover) is dealing with a object of a certain type.

For my breakpoint expression, I used:

`Std.is (this, ObjectType)`

where all instances of `this` are childclasses of FlxSprite.
However, that expression never triggers. It even does not when I set `ObjectType` to `FlxSprite`.

The breakpoint does trigger for simple numerical conditions, like:

`this.x < 25`

**Comment by sano98** [comment]
Used versions:

hxcpp: 4.0.8
hxcpp-debug-server: 1.1.1
lime: 7.2.1
openfl: 8.8.0
hscript: 2.3.0
haxe: 4.0.0-rc.1

**Comment by nulld** [comment]
For now, iterpreter, which executes expressions for conditional breakpoints has access only to properties of object, where breakpoint was hit, and know nothing about `Std.is`, for example. 

Maybe, some kind of custom initialization of interpreter will be usefull, how do you think?

For e.g. api can looks like:
```
DebugServer.interp_expose("Std", Std);
```

**Comment by Gama11** [comment]
Shouldn't we just expose top-level types such as `Std`, `Math`, etc by default?

**Comment by nulld** [comment]
Hm.. Sounds more user friendly than my solution - I like it :) But how many of top-level types average project use? It can significantly slowdown everything, if someone sets conditional breakpoint in game loop for e.g. ( For now, iterpreter initializes each time conditional breakpoint met )

**Comment by Gama11** [comment]
>For now, iterpreter initializes each time conditional breakpoint met

Why?

**Comment by sano98** [comment]
Just from a user perspective: When I run the debugger to identify a nasty problem, I generally don't care very much about slowdowns.

Once the problem is found, I can remove the breakpoint and everything should be back to full speed, right?

**Comment by nulld** [comment]
> Why?

Because, all varialbles with thier values, available in the line of breakpoint, need to be exposed to iterpreter.

**Comment by nulld** [comment]
I just thought, that we can hold all top-level types in static member of interpreter, and expose it once on debug session start - it must work pretty fast. Will try. 

Can I rename an issue?

**Comment by sano98** [comment]
About renaming: Are you asking for "permission"? Sure, rename as you see fit!

Or are you asking if it's possible to do it? I dunno; _I_ can rename it, as the one who created it, it seems.
If you can't - just let me know what you want it to be named

**Comment by nulld** [comment]
please test it with last commit, and reopen if it doesn't work for you for some reason

**Comment by Gama11** [comment]
Seems to basically work. :) But I guess right now stuff you want to use still needs to be exposed manually?

![](https://i.imgur.com/DoHG3Jg.png)

**Comment by Gama11** [comment]
I guess `cpp.vm.Debugger.getClasses()` must return an empty list in my case?

Anyway, I'll rename `staticVariables` to `globals` for now (since the classes you're adding to it aren't static vars) and make it read-only, and release a 1.2.0.

**Comment by nulld** [comment]
Found, that top-level types, declared inside hxcpp library, not presented in result of `cpp.vm.Debugger.getClasses()` call, so have add it manually (`Math`, `String`).

By the way, I have exposed other types too in order to use them in expressions, for e.g. `flixel.FlxSprite`.

**Comment by Gama11** [comment]
Seems to work great now. 👍

**Comment by sano98** [comment]
![grafik](https://user-images.githubusercontent.com/8257477/60325276-388e5f00-9987-11e9-944a-907937e9ee94.png)
When trying to use the condition with a classtype of my project, it does not trigger.
Am I missing something?
Does this not work, as my own classes are not exposed?
Is this a resolution thing - would I have to write the absolute file path of the Apple class?
Or is it generally not possible to do what I'm trying? Thx!

**Comment by nulld** [comment]
> would I have to write the absolute file path of the Apple class?
It should work, try path with package name.

пт, 28 июн. 2019 г. в 10:36, sano98 <notifications@github.com>:
