### ISSUE TITLE
hxcpp-debug-server incorrectly sends initialized event before initialize request has ended

### ISSUE THREAD

**Issue by joshtynjala** [vshaxe/hxcpp-debugger#24]
See [Initialized event in Debug Adapter Protocol specification](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized).

Relevant quote from spec:

> A debug adapter is expected to send this event when it is ready to accept configuration requests (but not before the ‘initialize’ request has finished).

As I understand it, this means that the "initialized" event should not be sent until after the response to the "initialize" request has been sent first.

I am currently trying to integrate this debug adapter with Moonshine IDE. I have already successfully integrated debug adapters for AIR and Flash Player, Chrome, and Firefox. Here is the sequence of messages, in order, that I'm logging from the protocol.

1. Initialize request from client (Moonshine IDE):

```
{"command":"initialize","type":"request","seq":1,"arguments":{"locale":"en-us","adapterID":"hxcpp","supportsMemoryReferences":false,"clientID":"moonshine","pathFormat":"path","supportsRunInTerminalRequest":false,"supportsVariableType":false,"supportsVariablePaging":false,"clientName":"Moonshine IDE","linesStartAt1":true,"columnsStartAt1":true}}
```

2. Initialized event from hxcpp-debug-server:

```
{"event":"initialized","type":"event","seq":1}
```

3. Response to initialize request from hxcpp-debug-server:

```
{"type":"response","body":{"supportsConditionalBreakpoints":true,"supportsValueFormattingOptions":false,"supportsSetVariable":true,"supportsCompletionsRequest":true},"command":"initialize","request_seq":1,"seq":2,"success":true}
```

Since the debug adapter currently works in VSCode, I guess that means that VScode is a bit more lenient than the spec. I will probably try to make Moonshine IDE allow the same behavior as VSCode. However, you may still want to adjust the debug adapter to match the spec, for maximum compatibility in the future.

**Comment by Gama11** [comment]
I'm curious if you've tried with any of the other vshaxe debug adapters / if any of those have the same issue (hashlink-debugger, eval-debugger, flash-debugger)?

**Comment by joshtynjala** [comment]
No, I haven't tried integrating any of the others yet. HashLink is on my to-do list, though.

**Comment by Gama11** [comment]
Please see if that commit helped.

**Comment by joshtynjala** [comment]
Looks good to me!
