### ISSUE TITLE
Make debug builds usable without debugging

### ISSUE THREAD

**Issue by Gama11** [vshaxe/hxcpp-debugger#3]
Right now, a debug build repeatedly tries to connect to the server when compiled with the `hxcpp-debug-server` lib and doesn't start until it does. This makes it unusable for anything but debugging, which can be a bit annoying.

One thing we could do is launch the executable with a `HXCPP_DEBUGGER` environment variable defined, and `Server` would only be instantiated if that env variable is present. However, that might cause issues when trying to support attach requests (#1).

@nulld Thoughts?

**Comment by Gama11** [comment]
The `Server.connect()` loop could maybe also be non-blocking to still allow the application to start? Probably enough to move it to `debuggerThreadMain` to allow for that. In that case, we might need a `stopOnEntry` property like the Node debugger has though so you have a way to make sure breakpoints on startup aren't missed.

**Comment by nulld** [comment]
I thought to limit number of tries will be enough, and start listening on same port for attach request if last try failed.

**Comment by Gama11** [comment]
Sure, that probably works too.
