### ISSUE TITLE
Strings containing Unicode crash on breakpoints.

### ISSUE THREAD

**Issue by EliteMasterEric** [vshaxe/hxcpp-debugger#31]
I encountered this while trying to process some data, and I've been able to reproduce a crash reliably:

## Reproduction

1. Create a simple program containing something like this:

```
var test = "Ω";
```

2. Place a breakpoint on the above line.

3. Start the program in debug mode. The program should pause and the variable scope should appear on the left alongside the call stack and watch list.

4. Step forward in the program.

## Expected Behavior

The user should see the variable `test` in the scope with the value `Ω`.

## Actual Behavior

The debugged program immediately crashes with no error message and the VSCode debugger detaches.

**Comment by mozsakalli** [comment]
FIX: Ut8 length is different than string.length so it crashes. Replace this method in Server.hx

	private function sendResponse(m:Message) {
		if (socket == null)
			return;

		socketMutex.acquire();
		var serialized:String = haxe.Json.stringify(m);
		var bytes = Bytes.ofString(serialized);
		socket.output.writeInt32(bytes.length);
		socket.output.writeBytes(bytes, 0, bytes.length);
		// socket.output.writeInt32(serialized.length);
		// socket.output.writeString(serialized);
		// trace('sendResponse: ${m.id} ${m.method}');
		socketMutex.release();
	}

**Comment by nulld** [comment]
Thanks for find a fix. Can you make a PR?
