### ISSUE TITLE
proper enum printing

### ISSUE THREAD

**Issue by nulld** [vshaxe/hxcpp-debugger#7]
At the moment all enum values represented as integers (index of enum value). It is preferable to print out values that wrapped in these enums, for example, there is enum `EExitConditio.GameTriggerGot(trigger:String, ?targetVarName:String);` which could be printed as a combination of name of the enum value and trigger and targetVarName values

**Comment by Gama11** [comment]
We can just use `Std.string()`:

![](https://i.imgur.com/17NUhue.png)
